### ISSUE TITLE
reflect bootstrap failed

### ISSUE THREAD

**Issue by liuhongda91** [onyx-intl/OnyxAndroidDemo#99]
W/ReflectUtil: java.lang.NoSuchFieldException: EINK_ONYX_AUTO_MASK
        at java.lang.Class.getField(Class.java:1604)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:1)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:20)
        at com.onyx.android.sdk.device.SDMDevice.createDevice(SourceFile:7)
        at com.onyx.android.sdk.device.Device.detectDevice(SourceFile:24)
        at com.onyx.android.sdk.device.Device.<clinit>(SourceFile:2)
        at com.onyx.android.sdk.device.Device.currentDevice(SourceFile:1)
        at com.onyx.android.sdk.api.device.epd.EpdController.enablePost(SourceFile:1)
        at com.android.onyx.demo.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:8064)
        at android.app.Activity.performCreate(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3459)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3638)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7778)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
W/droid.onyx.dem: Accessing hidden field Landroid/onyx/ViewUpdateHelper;->EINK_ONYX_GC_MASK:I (blacklist, reflection, denied)
W/ReflectUtil: java.lang.NoSuchFieldException: EINK_ONYX_GC_MASK
        at java.lang.Class.getField(Class.java:1604)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:1)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:20)
        at com.onyx.android.sdk.device.SDMDevice.createDevice(SourceFile:8)
        at com.onyx.android.sdk.device.Device.detectDevice(SourceFile:24)
        at com.onyx.android.sdk.device.Device.<clinit>(SourceFile:2)
        at com.onyx.android.sdk.device.Device.currentDevice(SourceFile:1)
        at com.onyx.android.sdk.api.device.epd.EpdController.enablePost(SourceFile:1)
        at com.android.onyx.demo.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:8064)
        at android.app.Activity.performCreate(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3459)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3638)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7778)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
W/droid.onyx.dem: Accessing hidden field Landroid/onyx/ViewUpdateHelper;->EINK_AUTO_MODE_REGIONAL:I (blacklist, reflection, denied)
W/ReflectUtil: java.lang.NoSuchFieldException: EINK_AUTO_MODE_REGIONAL
        at java.lang.Class.getField(Class.java:1604)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:1)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:20)
        at com.onyx.android.sdk.device.SDMDevice.createDevice(SourceFile:9)
        at com.onyx.android.sdk.device.Device.detectDevice(SourceFile:24)
        at com.onyx.android.sdk.device.Device.<clinit>(SourceFile:2)
        at com.onyx.android.sdk.device.Device.currentDevice(SourceFile:1)
        at com.onyx.android.sdk.api.device.epd.EpdController.enablePost(SourceFile:1)
        at com.android.onyx.demo.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:8064)
        at android.app.Activity.performCreate(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3459)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3638)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7778)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
W/droid.onyx.dem: Accessing hidden field Landroid/onyx/ViewUpdateHelper;->EINK_WAIT_MODE_NOWAIT:I (blacklist, reflection, denied)
W/ReflectUtil: java.lang.NoSuchFieldException: EINK_WAIT_MODE_NOWAIT
        at java.lang.Class.getField(Class.java:1604)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:1)
        at com.onyx.android.sdk.utils.ReflectUtil.getStaticIntFieldSafely(SourceFile:20)
        at com.onyx.android.sdk.device.SDMDevice.createDevice(SourceFile:10)
        at com.onyx.android.sdk.device.Device.detectDevice(SourceFile:24)
        at com.onyx.android.sdk.device.Device.<clinit>(SourceFile:2)
        at com.onyx.android.sdk.device.Device.currentDevice(SourceFile:1)
        at com.onyx.android.sdk.api.device.epd.EpdController.enablePost(SourceFile:1)
        at com.android.onyx.demo.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:8064)
        at android.app.Activity.performCreate(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3459)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3638)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7778)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
W/droid.onyx.dem: Accessing hidden field Landroid/onyx/ViewUpdateHelper;->EINK_WAVEFORM_MODE_ANIM:I (blacklist, reflection, denied)

**Comment by liuhongda91** [comment]
> 

not yet. any ideas?

**Comment by joshua211** [comment]
Seems to work even with all those exceptions, so im ignoring it for now
